categories: [Epigenetics]
description: Mapping Ilumina methylation array data to the genome using an annotation
  package. Depending on the genome, not all methylation loci may have a genomic position.
homepage_url: https://github.com/kpbioteam/minfi_maptogenome
name: minfi_maptogenome
owner: kpbioteam
remote_repository_url: https://github.com/kpbioteam/minfi_maptogenome
